export { default as lingolink } from "../images/lingolink.svg";
export { default as banana } from "../images/banana.svg";
export { default as nail } from "../images/nail.svg";
export { default as chakra } from "../images/chakra.svg";
export { default as carRental } from "../images/carRental.svg";
export { default as profile } from "../images/profile.svg";
export { default as p1 } from "../images/p1.svg";
export { default as p2 } from "../images/p2.svg";
export { default as p3 } from "../images/p3.svg";
